#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

cookbook 'main',
        	:path => 'cookbooks-sources'


cookbook 'redisio'
cookbook 'apt'

cookbook 'ulimit',
					:path => 'cookbooks-sources'

cookbook 'rbenv',:git=>'git://github.com/fnichol/chef-rbenv.git'
cookbook 'ruby_build',:github=>'fnichol/chef-ruby_build',:ref=>'v0.7.2'
cookbook 'build-essential'
cookbook 'runit'
cookbook 'chef_handler'
cookbook 'git'
cookbook 'bluepill'
cookbook 'ohai'




# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
